name: BUILD
on: 
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - '**.md'
      - '**.txt'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - "docs/**"
      - '**.md'
      - '**.txt'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-gnu-static","x86_64-unknown-linux-musl","aarch64-unknown-linux-musl"]
        include:
          - target: "x86_64-unknown-linux-gnu"
            triple: "x86_64-unknown-linux-gnu"
            static: false
          - target: "x86_64-unknown-linux-gnu-static"
            triple: "x86_64-unknown-linux-gnu"
            static: true
          - target: "x86_64-unknown-linux-musl"
            triple: "x86_64-unknown-linux-musl"
            static: true
          - target: "aarch64-unknown-linux-musl"
            triple: "aarch64-unknown-linux-musl"
            static: true
          - target: "loongarch64-unknown-linux-musl"
            triple: "loongarch64-unknown-linux-musl"
            static: true
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Setup nu
        uses: hustcer/setup-nu@v3
        with:
          version: 0.109.1
      - name: Compile Git
        run: |
          ./build.sh --target ${{ matrix.triple }} --static ${{ matrix.static }}
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          file: out/*
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true

      
